name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurando Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalando as dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executando Testes
      run: |
        pytest

    - name: Contruindo a imagem do docker
      if: success()
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/desafio-neoway:latest .

    - name: Logando no docker hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Fazendo o upload da nova imagem
      if: success()
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/desafio-neoway:latest